name: Welcome New Contributor

on:
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet first-time contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            👋 Hello! Thank you for opening your first pull request!  
            We appreciate your contribution.  
            Please make sure to follow our contribution guidelines.
